spring.application.name=jms-example

spring.jms.template.default-destination=hello-world-queue
spring.artemis.embedded.persistent=true
spring.artemis.embedded.data-directory=target/data/journal

jms.queue.send-to=hello-world-queue
jms.queue.reply-to=reply-back-to-me